/// Protocol-level opcode ops consumption params.
#[derive(Clone, Debug)]
pub struct OpcodeOpsParams {
    pub op_false: u64,
    pub op_true: u64,
    pub op_2: u64,
    pub op_3: u64,
    pub op_4: u64,
    pub op_5: u64,
    pub op_6: u64,
    pub op_7: u64,
    pub op_8: u64,
    pub op_9: u64,
    pub op_10: u64,
    pub op_11: u64,
    pub op_12: u64,
    pub op_13: u64,
    pub op_14: u64,
    pub op_15: u64,
    pub op_16: u64,
    pub op_pushdata_base: u64,
    pub op_pushdata_per_byte: u64,
    pub op_nop: u64,
    pub op_jump: u64,
    pub op_if: u64,
    pub op_notif: u64,
    pub op_else: u64,
    pub op_endif: u64,
    pub op_verify: u64,
    pub op_returnall: u64,
    pub op_returnsome: u64,
    pub op_fail: u64,
    pub op_returnerr: u64,
    pub op_toaltstack: u64,
    pub op_fromaltstack: u64,
    pub op_2drop: u64,
    pub op_2dup: u64,
    pub op_3dup: u64,
    pub op_2over: u64,
    pub op_2rot: u64,
    pub op_2swap: u64,
    pub op_ifdup: u64,
    pub op_depth: u64,
    pub op_drop: u64,
    pub op_dup: u64,
    pub op_nip: u64,
    pub op_over: u64,
    pub op_pick: u64,
    pub op_roll: u64,
    pub op_rot: u64,
    pub op_swap: u64,
    pub op_tuck: u64,
    pub op_cat: u64,
    pub op_split: u64,
    pub op_left: u64,
    pub op_right: u64,
    pub op_size: u64,
    pub op_invert: u64,
    pub op_and: u64,
    pub op_or: u64,
    pub op_xor: u64,
    pub op_equal: u64,
    pub op_equalverify: u64,
    pub op_reverse: u64,
    pub op_1add: u64,
    pub op_1sub: u64,
    pub op_2mul: u64,
    pub op_2div: u64,
    pub op_addmod: u64,
    pub op_mulmod: u64,
    pub op_not: u64,
    pub op_0notequal: u64,
    pub op_add: u64,
    pub op_sub: u64,
    pub op_mul: u64,
    pub op_div: u64,
    pub op_lshift: u64,
    pub op_rshift: u64,
    pub op_booland: u64,
    pub op_boolor: u64,
    pub op_numequal: u64,
    pub op_numequalverify: u64,
    pub op_numnotequal: u64,
    pub op_lessthan: u64,
    pub op_greaterthan: u64,
    pub op_lessthanorequal: u64,
    pub op_greaterthanorequal: u64,
    pub op_min: u64,
    pub op_max: u64,
    pub op_within: u64,
    pub op_mread: u64,
    pub op_mwrite: u64,
    pub op_mfree: u64,
    pub op_ripemd160: u64,
    pub op_sha1: u64,
    pub op_sha256: u64,
    pub op_hash160: u64,
    pub op_hash256: u64,
    pub op_taggedhash_base: u64,
    pub op_taggedhash_per_byte_gap: u64,
    pub op_taggedhash_output_len: u64,
    pub op_blake2bvar_base: u64,
    pub op_blake2bvar_per_byte: u64,
    pub op_blake2svar_base: u64,
    pub op_blake2svar_per_byte: u64,
    pub op_secpscalaradd: u64,
    pub op_secpscalarmul: u64,
    pub op_secppointadd: u64,
    pub op_secppointmul: u64,
    pub op_pushsecpgeneratorpoint: u64,
    pub op_iszerosecpscalar: u64,
    pub op_isinfinitesecppoint: u64,
    pub op_checkschnorrsig: u64,
    pub op_checkschnorrsigbip340: u64,
    pub op_checkblssig: u64,
    pub op_checkblssigagg_base: u64,
    pub op_checkblssigagg_per_count: u64,
    pub op_caller: u64,
    pub op_opsbudget: u64,
    pub op_opscounter: u64,
    pub op_opsprice: u64,
    pub op_timestamp: u64,
    pub op_call: u64,
    pub op_callext: u64,
    pub op_sread: u64,
    pub op_sfree: u64,
    pub op_swrite_base: u64,
    pub op_swrite_per_byte: u64,
    pub op_shadow_alloc: u64,
    pub op_shadow_dealloc: u64,
    pub op_shadow_has_alloc: u64,
    pub op_shadow_alloc_val: u64,
    pub op_shadow_up: u64,
    pub op_shadow_down: u64,
    pub op_shadow_up_all: u64,
    pub op_shadow_down_all: u64,
    pub op_shadow_num_allocs: u64,
    pub op_shadow_allocs_sum: u64,
    pub op_ext_balance: u64,
    pub op_self_balance: u64,
    pub op_transfer: u64,
    pub op_update_param: u64,
    pub op_gov_account: u64,
    pub op_gov_contract: u64,
    pub op_reconstitute: u64,
}

impl OpcodeOpsParams {
    /// Default opcode ops values used at chain origin.
    pub fn origin() -> Self {
        Self {
            op_false: 1,
            op_true: 1,
            op_2: 1,
            op_3: 1,
            op_4: 1,
            op_5: 1,
            op_6: 1,
            op_7: 1,
            op_8: 1,
            op_9: 1,
            op_10: 1,
            op_11: 1,
            op_12: 1,
            op_13: 1,
            op_14: 1,
            op_15: 1,
            op_16: 1,
            op_pushdata_base: 1,
            op_pushdata_per_byte: 1,
            op_nop: 1,
            op_jump: 1,
            op_if: 1,
            op_notif: 1,
            op_else: 1,
            op_endif: 1,
            op_verify: 1,
            op_returnall: 1,
            op_returnsome: 1,
            op_fail: 1,
            op_returnerr: 1,
            op_toaltstack: 1,
            op_fromaltstack: 1,
            op_2drop: 2,
            op_2dup: 2,
            op_3dup: 3,
            op_2over: 2,
            op_2rot: 2,
            op_2swap: 2,
            op_ifdup: 1,
            op_depth: 1,
            op_drop: 1,
            op_dup: 1,
            op_nip: 1,
            op_over: 1,
            op_pick: 1,
            op_roll: 1,
            op_rot: 1,
            op_swap: 1,
            op_tuck: 1,
            op_cat: 2,
            op_split: 2,
            op_left: 2,
            op_right: 2,
            op_size: 1,
            op_invert: 2,
            op_and: 2,
            op_or: 2,
            op_xor: 2,
            op_equal: 1,
            op_equalverify: 2,
            op_reverse: 3,
            op_1add: 3,
            op_1sub: 3,
            op_2mul: 5,
            op_2div: 5,
            op_addmod: 3,
            op_mulmod: 3,
            op_not: 1,
            op_0notequal: 1,
            op_add: 3,
            op_sub: 3,
            op_mul: 5,
            op_div: 5,
            op_lshift: 3,
            op_rshift: 3,
            op_booland: 2,
            op_boolor: 2,
            op_numequal: 1,
            op_numequalverify: 2,
            op_numnotequal: 1,
            op_lessthan: 1,
            op_greaterthan: 1,
            op_lessthanorequal: 1,
            op_greaterthanorequal: 1,
            op_min: 1,
            op_max: 1,
            op_within: 1,
            op_mread: 5,
            op_mwrite: 5,
            op_mfree: 1,
            op_ripemd160: 30,
            op_sha1: 30,
            op_sha256: 42,
            op_hash160: 72,
            op_hash256: 84,
            op_taggedhash_base: 10,
            op_taggedhash_per_byte_gap: 1,
            op_taggedhash_output_len: 32,
            op_blake2bvar_base: 10,
            op_blake2bvar_per_byte: 1,
            op_blake2svar_base: 10,
            op_blake2svar_per_byte: 1,
            op_secpscalaradd: 3,
            op_secpscalarmul: 5,
            op_secppointadd: 10,
            op_secppointmul: 10,
            op_pushsecpgeneratorpoint: 1,
            op_iszerosecpscalar: 1,
            op_isinfinitesecppoint: 1,
            op_checkschnorrsig: 100,
            op_checkschnorrsigbip340: 100,
            op_checkblssig: 100,
            op_checkblssigagg_base: 100,
            op_checkblssigagg_per_count: 50,
            op_caller: 1,
            op_opsbudget: 1,
            op_opscounter: 1,
            op_opsprice: 1,
            op_timestamp: 1,
            op_call: 5,
            op_callext: 50,
            op_sread: 50,
            op_sfree: 1,
            op_swrite_base: 50,
            op_swrite_per_byte: 1,
            op_shadow_alloc: 1000,
            op_shadow_dealloc: 900,
            op_shadow_has_alloc: 1,
            op_shadow_alloc_val: 1,
            op_shadow_up: 5,
            op_shadow_down: 5,
            op_shadow_up_all: 50,
            op_shadow_down_all: 50,
            op_shadow_num_allocs: 1,
            op_shadow_allocs_sum: 1,
            op_ext_balance: 1,
            op_self_balance: 1,
            op_transfer: 10,
            op_update_param: 100,
            op_gov_account: 100,
            op_gov_contract: 100,
            op_reconstitute: 100,
        }
    }

    /// Converts a stored u64 param to u32 for runtime ops accounting.
    #[inline]
    pub fn as_u32(value: u64) -> u32 {
        value.min(u32::MAX as u64) as u32
    }
}
